[build]
  command = "docker build -t expenseowl-builder . && docker run --rm -v $(pwd)/netlify/functions:/output expenseowl-builder cp /app/bootstrap /output/expenseowl"
  functions = "netlify/functions"
  publish = "/"

[build.environment]
  GO_VERSION = "1.23" # Keep this for the Go version inside the container

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/expenseowl"
  status = 200
